import type { Row } from '../registry';

export const ME_ROUTES: Row[] = [
  {
    method: 'GET',
    path: '/me',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: 'none',
    invalid: 'none',
  },
  {
    method: 'PATCH',
    path: '/me/locale',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: 'none',
    invalid: {
      body: { locale: 'fr' },
      fields: [
        {
          field: 'locale',
          code: 'INVALID_VALUE',
          params: { allowed: ['ar', 'en'] },
        },
      ],
    },
  },
  {
    method: 'GET',
    path: '/me/units',
    auth: 'tenant',
    as: 'family',
    denied: 'none',
    foreign: 'none',
    invalid: 'none',
  },
  {
    method: 'GET',
    path: '/me/units/{unitId}/capabilities',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: {
      params: (w) => ({ unitId: w.b.homeUnitId }),
      code: 'UNIT_NOT_FOUND',
    },
    invalid: 'none',
  },
  {
    method: 'GET',
    path: '/me/units/{unitId}/permissions',
    auth: 'tenant',
    as: 'family',
    denied: 'none',
    foreign: {
      params: (w) => ({ unitId: w.b.homeUnitId }),
      code: 'UNIT_NOT_FOUND',
    },
    invalid: 'none',
  },
  {
    method: 'GET',
    path: '/me/delegations',
    auth: 'tenant',
    as: 'family',
    denied: 'none',
    foreign: 'none',
    invalid: 'none',
  },
  {
    method: 'GET',
    path: '/me/sessions',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: 'none',
    invalid: 'none',
  },
  {
    method: 'POST',
    path: '/me/sessions/{id}/revoke',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: {
      params: (w) => ({ id: w.b.sessions.owner }),
      code: 'SESSION_NOT_FOUND',
    },
    invalid: 'none',
  },
  {
    method: 'POST',
    path: '/me/sessions/revoke-all',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: 'none',
    invalid: 'none',
  },
  {
    method: 'GET',
    path: '/me/deletion-request',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: 'none',
    invalid: 'none',
  },
  {
    method: 'POST',
    path: '/me/deletion-request',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: 'none',
    invalid: {
      body: { confirmation: '' },
      fields: [
        {
          field: 'confirmation',
          code: 'INVALID_LENGTH',
          params: { min: 1, max: 50 },
        },
      ],
    },
  },
  {
    method: 'POST',
    path: '/me/deletion-request/cancel',
    auth: 'tenant',
    as: 'owner',
    denied: 'none',
    foreign: 'none',
    invalid: 'none',
  },
];
